---
- name: Copy index.html file
  copy:
    src: /etc/ansible/index.html
    dest: /var/www/html/index.html
    mode: "0644"

- name: Start Apache service
  service:
    name: apache2
    state: started
    enabled: yes
