---
- name: Install and Configure Apache on Ubuntu
  hosts: webservers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache package
      apt:
        name: apache2
        state: present

    - name: Copy index.html file
      copy:
        src: /etc/ansible/index.html
        dest: /var/www/html/index.html
        mode: "0644"

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes


