apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany   # ReadWriteOnce, ReadWriteMany, and ReadOnlyMany.
  storageClassName: my-azurefile-sc
  resources:
    requests:
      storage: 5Gi